### ISSUE TITLE
Why is interpolation necessary?

### ISSUE THREAD

**Issue by shaform** [kodalinaveen3/DRAGAN#5]
```python
interpolates = X + (alpha*differences)
= X + U[0, 1] (X_p - X)
= X + U[0, 1](X + 0.5*std * U[0,1] - X)
= X + U[0, 1] * 0.5 std * U[0, 1]
= X + 0.5 * std * U[0, 1]^2
~= X_p
```
so it appears that X_p can be directly used instead of interpolates.

And the paper actually used `X_p` instead of interpolates.

**Comment by kodalinaveen3** [comment]
Yes! We will be releasing updated version of our paper next week. The first draft was done in haste, while shooting for a conference deadline
